"""Guards for token_kit.prompts -- the verbatim user-prompt extractor.

The fixture transcript is BUILT HERE, record by record, and never copied from a
real one: a real transcript is the user's own words, and the repository is the
last place they belong. Every record shape below was read off a live transcript
first, then written down as a constructor.

What is pinned:
  * one test per exclusion class, so a class that silently stops excluding is a
    failure and not a surprise in the output;
  * `<system-reminder>` blocks are stripped out of a prompt that is otherwise
    the user's;
  * a resumed session, which repeats its history verbatim, produces each prompt
    ONCE -- the uuid is the identity, not the file;
  * a torn last line is counted, not fatal;
  * two runs over the same transcripts write identical bytes;
  * an oversized prompt is cut WITH a marker naming the bytes lost;
  * `--since` keeps the boundary day and drops the day before.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

KIT_DIR = Path(__file__).resolve().parent.parent
if str(KIT_DIR / "src") not in sys.path:
    sys.path.insert(0, str(KIT_DIR / "src"))

from token_kit import prompts as P  # noqa: E402
from token_kit.router.hook import slug  # noqa: E402

SESSION = "11111111-2222-3333-4444-555555555555"


def rec(uuid, text, when="2026-01-31T14:05:00.000Z", session=SESSION, **extra):
    """One `type: "user"` record, in the shape the CLI writes."""
    out = {"parentUuid": None, "isSidechain": False, "type": "user",
           "message": {"role": "user", "content": text},
           "uuid": uuid, "timestamp": when, "userType": "external",
           "sessionId": session, "cwd": "/somewhere", "version": "2.1.278"}
    out.update(extra)
    return out


def blocks(uuid, *content, **extra):
    """A record whose content is a LIST of blocks, the other real shape."""
    r = rec(uuid, "", **extra)
    r["message"]["content"] = list(content)
    return r


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.cwd = self.root / "work"
        self.cwd.mkdir()
        self.projects = self.root / "projects"
        self.session_dir = self.projects / slug(str(self.cwd.resolve()))
        self.session_dir.mkdir(parents=True)

    def tearDown(self):
        self.tmp.cleanup()

    def write(self, name, records, tail=""):
        path = self.session_dir / f"{name}.jsonl"
        with path.open("w", encoding="utf-8") as fh:
            for r in records:
                fh.write(json.dumps(r) + "\n")
            if tail:
                fh.write(tail)
        return path

    def collect(self, **kw):
        return P.collect(str(self.cwd), self.projects, **kw)


class Exclusions(Base):
    """One case per name in P.EXCLUSIONS. Each shape was seen in a real file."""

    def test_a_plain_typed_prompt_is_kept(self):
        """The guard that arms all the others: something must survive."""
        self.write("s", [rec("u1", "where are the user prompts recorded?",
                             promptSource="typed")])
        got, stats = self.collect()
        self.assertEqual(["where are the user prompts recorded?"],
                         [p.text for p in got])
        self.assertEqual(1, stats.kept)

    def test_tool_results_are_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            blocks("u2", {"tool_use_id": "toolu_1", "type": "tool_result",
                          "content": "login009\n"},
                   toolUseResult={"stdout": "login009"}),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(1, stats.excluded["tool_result"])

    def test_meta_records_are_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "<local-command-caveat>Caveat: The messages below were "
                      "generated by the user while running local commands."
                      "</local-command-caveat>", isMeta=True),
            rec("u3", "Another Claude session sent a message:\n"
                      "<agent-message from=\"a2feb38bd3d126095\">report</agent-message>",
                isMeta=True),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(2, stats.excluded["meta"])

    def test_sidechain_records_are_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "You are a subagent. Do the thing.", isSidechain=True),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(1, stats.excluded["sidechain"])

    def test_compaction_summaries_are_excluded_both_ways(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "This session is being continued from a previous "
                      "conversation that ran out of context.\n\nSummary:\n1. ..."),
            rec("u3", "some other summary text", isCompactSummary=True),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(2, stats.excluded["compact_summary"])

    def test_system_sourced_records_are_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "Hourly check-in. Every claim is a lead to verify.",
                promptSource="system"),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(1, stats.excluded["system_prompt"])

    def test_task_notifications_are_excluded(self):
        """Older records carry no promptSource, so the tag must stand alone."""
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "<task-notification>\n<task-id>a1703a032b31d7400</task-id>\n"
                      "<output-file>/tmp/x</output-file>\n</task-notification>"),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(1, stats.excluded["task_notification"])

    def test_local_command_output_is_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "<local-command-stdout>Login successful</local-command-stdout>"),
            rec("u3", "<bash-stdout>(Bash completed with no output)</bash-stdout>"),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(2, stats.excluded["command_output"])

    def test_hook_feedback_is_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "<user-prompt-submit-hook>budget: 41 calls used"
                      "</user-prompt-submit-hook>"),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(1, stats.excluded["hook_feedback"])

    def test_interrupt_markers_are_excluded(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            rec("u2", "[Request interrupted by user]"),
            rec("u3", "[Request interrupted by user for tool use]"),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(2, stats.excluded["interrupt_marker"])

    def test_a_reminder_only_record_is_empty_and_not_a_prompt(self):
        self.write("s", [
            rec("u1", "keep me", promptSource="typed"),
            blocks("u2", {"type": "text",
                          "text": "<system-reminder>Your final report is "
                                  "delivered through SubagentHandback."
                                  "</system-reminder>"}),
        ])
        got, stats = self.collect()
        self.assertEqual(["keep me"], [p.text for p in got])
        self.assertEqual(1, stats.excluded["empty"])

    def test_every_named_exclusion_class_has_a_case_here(self):
        """A class added to the module without a guard is a defect."""
        names = {n for n in P.EXCLUSIONS}
        covered = set()
        for name in names:
            for attr in dir(self):
                if attr.startswith("test_") and name.split("_")[0] in attr:
                    covered.add(name)
        self.assertEqual(names, covered, f"uncovered exclusion classes: {names - covered}")


class KeptText(Base):
    def test_a_system_reminder_is_stripped_from_inside_a_real_prompt(self):
        self.write("s", [rec("u1",
                             "fix the thing\n<system-reminder>The user opened "
                             "a file.</system-reminder>\nand then ship it",
                             promptSource="typed")])
        got, _ = self.collect()
        self.assertEqual("fix the thing\n\nand then ship it", got[0].text)
        self.assertNotIn("system-reminder", got[0].text)

    def test_a_slash_command_keeps_only_its_name_and_args(self):
        self.write("s", [rec("u1",
                             "<command-name>/loop</command-name>\n"
                             "            <command-message>loop</command-message>\n"
                             "            <command-args>5m /status</command-args>")])
        got, _ = self.collect()
        self.assertEqual("/loop 5m /status", got[0].text)

    def test_a_pasted_block_is_kept_whole(self):
        pasted = "<pasted_content id=\"ea64\">\n" + "line\n" * 50 + "</pasted_content>"
        self.write("s", [rec("u1", pasted, promptSource="typed")])
        got, _ = self.collect()
        self.assertIn("pasted_content", got[0].text)
        self.assertEqual(50, got[0].text.count("line\n"))


class Robustness(Base):
    def test_a_torn_line_is_counted_not_fatal(self):
        self.write("s", [rec("u1", "before the tear", promptSource="typed")],
                   tail='{"type": "user", "message": {"role": "user", "cont')
        got, stats = self.collect()
        self.assertEqual(["before the tear"], [p.text for p in got])
        self.assertEqual(1, stats.torn)

    def test_a_resumed_session_repeats_history_and_is_de_duplicated(self):
        first = [rec("u1", "the first thing", when="2026-01-31T10:00:00.000Z",
                     promptSource="typed"),
                 rec("u2", "the second thing", when="2026-01-31T11:00:00.000Z",
                     promptSource="typed")]
        self.write("aaaa", first)
        # A resume copies every earlier record forward, uuids and all.
        self.write("bbbb", first + [rec("u3", "the third thing",
                                        when="2026-01-31T12:00:00.000Z",
                                        session="other", promptSource="typed")])
        got, stats = self.collect()
        self.assertEqual(["the first thing", "the second thing", "the third thing"],
                         [p.text for p in got])
        self.assertEqual(2, stats.duplicates)
        self.assertEqual(2, stats.files)

    def test_output_is_byte_identical_on_a_second_run(self):
        self.write("s", [rec("u2", "second", when="2026-01-31T12:00:00.000Z",
                             promptSource="typed"),
                         rec("u1", "first", when="2026-01-31T10:00:00.000Z",
                             promptSource="typed")])
        out = self.cwd / "PROMPTS.md"
        P.refresh(str(self.cwd), out, self.projects)
        once = out.read_bytes()
        P.refresh(str(self.cwd), out, self.projects)
        self.assertEqual(once, out.read_bytes())
        # and chronological regardless of the order on disk
        self.assertLess(once.decode().index("first"), once.decode().index("second"))

    def test_the_file_is_written_0600(self):
        self.write("s", [rec("u1", "private", promptSource="typed")])
        out = self.cwd / "PROMPTS.md"
        out.write_text("world readable")
        os.chmod(out, 0o644)
        P.refresh(str(self.cwd), out, self.projects)
        self.assertEqual(0o600, out.stat().st_mode & 0o777)

    def test_an_oversized_prompt_is_cut_with_a_marker(self):
        self.write("s", [rec("u1", "x" * 500, promptSource="typed")])
        got, _ = self.collect()
        text = P.render(got, str(self.cwd), limit=100)
        self.assertIn(P.CUT_MARKER.format(n=400), text)
        self.assertNotIn("x" * 200, text)

    def test_since_keeps_the_boundary_day_and_drops_the_day_before(self):
        self.write("s", [rec("u1", "day before", when="2026-01-30T18:00:00.000Z",
                             promptSource="typed"),
                         rec("u2", "boundary day", when="2026-01-31T18:00:00.000Z",
                             promptSource="typed")])
        got, _ = self.collect(since="2026-01-31")
        self.assertEqual(["boundary day"], [p.text for p in got])

    def test_one_session_only(self):
        self.write("aaaa", [rec("u1", "in aaaa", promptSource="typed")])
        self.write("bbbb", [rec("u2", "in bbbb", session="bbbb",
                                promptSource="typed")])
        got, _ = self.collect(session="bbbb")
        self.assertEqual(["in bbbb"], [p.text for p in got])

    def test_a_directory_with_no_transcripts_is_an_empty_file_not_a_crash(self):
        out = self.cwd / "PROMPTS.md"
        stats = P.refresh(str(self.cwd / "nothing-here"), out, self.projects)
        self.assertEqual(0, stats.kept)
        self.assertIn("What the user said", out.read_text())


class Rendering(Base):
    def test_an_entry_is_a_dated_heading_and_a_blockquote(self):
        self.write("s", [rec("u1", "line one\n\nline two", promptSource="typed")])
        got, _ = self.collect()
        text = P.render(got, str(self.cwd))
        self.assertIn(f"· {SESSION[:8]}", text)
        self.assertIn("> line one", text)
        self.assertIn("> line two", text)
        # A person reads this file: the date is a heading, the clock is human.
        self.assertRegex(text, r"## [A-Z][a-z]{2} \d{1,2} [A-Z][a-z]{2} \d{4}\n")
        self.assertRegex(text, r"### \d{1,2}:\d{2}[ap]m · ")


if __name__ == "__main__":
    unittest.main()
